version: '3.4'

services:
  zpmini:
    image: zpmini
    container_name: zpmini
    build: .
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Develop
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "@Thisisatest123daw1@"
      ACCEPT_EULA: "Y"
      MYSQL_ROOT_HOST: '%'
    ports:
      - 1401:1443