version: '3.4'

services:
  zpmini.api:
    image: ${DOCKER_REGISTRY-}zpminiapi
    container_name: zpmini
    ports:
      - 80:80
    build:
      context: .
      dockerfile: ZPMini/Dockerfile
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "@Thisisatest123daw1@"
      ACCEPT_EULA: "Y"
      MYSQL_ROOT_HOST: '%'
    ports:
      - 1401:1443